# a base github action
name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build image
        run: docker build -t image .
      - name: Run buildroot
        run: docker run --rm --name builder -v $PWD/dist:/build -v $PWD/buildroot-v86/:/buildroot-v86 image -- make clean all
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: positive-parade-${{ github.run_number }}
          if-no-files-found: error